return {
  { "NMAC427/guess-indent.nvim",               enabled = false,           opts = {} },
  { "stevearc/aerial.nvim",                    enabled = false,           opts = {} },
  { "rebelot/heirline.nvim",                   enabled = false,           opts = {} },
  { "echasnovski/mini.statusline",             version = false,           opts = {} },
  { "echasnovski/mini.tabline",                version = false,           opts = {} },
  { "akinsho/toggleterm.nvim",                 enabled = false },
  { "nvim-neo-tree/neo-tree.nvim",             enabled = false },
  { "s1n7ax/nvim-window-picker",               enabled = false },
  { "famiu/bufdelete.nvim",                    enabled = false },
  { "nvim-treesitter/nvim-treesitter-context", lazy = false },
  { "mbbill/undotree",                         cmd = { "UndotreeToggle" } },
  { "mrjones2014/smart-splits.nvim",           enabled = false },
  { "echasnovski/mini.surround",               version = false,           opts = {} },
  {
    "christoomey/vim-tmux-navigator",
    cmd = {
      "TmuxNavigateLeft",
      "TmuxNavigateDown",
      "TmuxNavigateUp",
      "TmuxNavigateRight",
      "TmuxNavigatePrevious",
    },
  },
  {
    "Exafunction/codeium.nvim",
    lazy = false,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "hrsh7th/nvim-cmp",
    },
    opts = {},
  },
  { "dylanaraps/fff.vim",              cmd = "F" },
  { "ckipp01/nvim-jenkinsfile-linter", requires = { "nvim-lua/plenary.nvim" }, lazy = false },
}
