return {
  Normal = { bg = "NONE", ctermbg = "NONE" },
  NormalNC = { bg = "NONE", ctermbg = "NONE" },
  NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
  NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
  CursorColumn = { cterm = {}, ctermbg = 00000, ctermfg = "NONE" },
  CursorLine = { cterm = {}, ctermbg = 00000, ctermfg = "NONE" },
  -- CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  -- LineNr = {},
  -- SignColumn = {},
  -- StatusLine = {},
  TelescopeMatching = { fg = "#66A7E3" },
  TelescopeSelection = { fg = "#C074DC", bg = "#080406", bold = true },
  TelescopePromptPrefix = { bg = 00000 },
  TelescopePromptNormal = { bg = 00000 },
  TelescopeResultsNormal = { bg = 00000 },
  TelescopePreviewNormal = { bg = 00000 },
  TelescopePromptBorder = { bg = 00000, fg = "#C074DC" },
  TelescopeResultsBorder = { bg = 00000, fg = "#C074DC" },
  TelescopePreviewBorder = { bg = "NONE", fg = "#C074DC" },
}
