local c = {
  transparent = "NONE",
  foreground = "#a9b1d6",
  background = "#000",
  color0 = "#414868",
  color8 = "#414868",
  color1 = "#f7768e",
  color9 = "#f7768e",
  color2 = "#73daca",
  color10 = "#73daca",
  color3 = "#e0af68",
  color11 = "#e0af68",
  color4 = "#7aa2f7",
  color12 = "#7aa2f7",
  color5 = "#bb9af7",
  color13 = "#bb9af7",
  color6 = "#7dcfff",
  color14 = "#7dcfff",
  color7 = "#c0caf5",
  color15 = "#c0caf5",
  cursor = "#c0caf5",
  cursor_text_color = "#1a1b26",
  selection_foreground = "#7aa2f7",
  selection_background = "#28344a",
}
return {
  Normal = { bg = c.transparent, ctermbg = c.transparent },
  NormalNC = { bg = c.transparent, ctermbg = c.transparent },
  NeoTreeNormal = { bg = c.transparent, ctermbg = c.transparent },
  NeoTreeNormalNC = { bg = c.transparent, ctermbg = c.transparent },
  CursorColumn = { cterm = {}, ctermbg = 00000, ctermfg = c.transparent },
  CursorLine = { cterm = {}, ctermbg = 00000, ctermfg = c.transparent },
  -- CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  -- LineNr = {},
  -- SignColumn = {},
  -- StatusLine = {},
  TelescopeMatching = { fg = c.selection_foreground },
  TelescopeSelection = { fg = c.color5, bg = c.color0, bold = true },
  TelescopePromptPrefix = { bg = 00000 },
  TelescopePromptNormal = { bg = 00000 },
  TelescopeResultsNormal = { bg = 00000 },
  TelescopePreviewNormal = { bg = 00000 },
  TelescopePromptBorder = { bg = 00000, fg = 00000 },
  TelescopeResultsBorder = { bg = 00000, fg = 00000 },
  TelescopePreviewBorder = { bg = c.transparent, fg = 00000 },
}
