local C = require("astronvim.utils.status.env").fallback_colors
-- none = "NONE",
-- fg = "#abb2bf",
-- bg = "#1e222a",
-- dark_bg = "#2c323c",
-- blue = "#61afef",
-- green = "#98c379",
-- grey = "#5c6370",
-- bright_grey = "#777d86",
-- dark_grey = "#5c5c5c",
-- orange = "#ff9640",
-- purple = "#c678dd",
-- bright_purple = "#a9a1e1",
-- red = "#e06c75",
-- bright_red = "#ec5f67",
-- white = "#c9c9c9",
-- yellow = "#e5c07b",
-- bright_yellow = "#ebae34",

return {
  Normal = { bg = C.none, ctermbg = C.none },
  NormalNC = { bg = C.none, ctermbg = C.none },
  NeoTreeNormal = { bg = C.none, ctermbg = C.none },
  NeoTreeNormalNC = { bg = C.none, ctermbg = C.none },
  CursorColumn = { cterm = {}, ctermbg = 00000, ctermfg = C.none },
  CursorLine = { cterm = {}, ctermbg = 00000, ctermfg = C.none },
  -- CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
  -- LineNr = {},
  -- SignColumn = {},
  -- StatusLine = {},
  TelescopeMatching = { fg = C.green },
  TelescopeSelection = { fg = C.purple, bg = C.none, bold = true },
  TelescopePromptPrefix = { bg = 00000 },
  TelescopePromptNormal = { bg = 00000 },
  TelescopeResultsNormal = { bg = 00000 },
  TelescopePreviewNormal = { bg = 00000 },
  TelescopePromptBorder = { bg = 00000, fg = 00000 },
  TelescopeResultsBorder = { bg = 00000, fg = 00000 },
  TelescopePreviewBorder = { bg = C.none, fg = 00000 },
}
